apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-site
data:
  index.html: |
{{ .Files.Get "files/index.html" | indent 4 }}
binaryData:
  cv.pdf: {{ .Files.Get "files/cv.pdf" | b64enc }}
