all:
  vars:
    ansible_user: packer
    ansible_become: true
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    calico_vxlan_mode: Always
    calico_ipip_mode: Never
    calico_backend: vxlan
    supplementary_addresses_in_ssl_keys:
      - "{{ lookup('env', 'HOST1_IP') }}"
      # - "{{ lookup('env', 'HOST2_IP') }}"
  hosts:
    node1:
      ansible_host: "192.168.122.10"
      ip: "192.168.122.10"
      ansible_ssh_common_args: >-
        -o StrictHostKeyChecking=accept-new
        -o ProxyCommand="ssh -o StrictHostKeyChecking=accept-new -W %h:%p ubuntu@{{ lookup('env', 'HOST1_IP') }}"
    # node2:
    #   ansible_host: "192.168.122.11"
    #   ip: "192.168.122.11"
    #   ansible_ssh_common_args: >-
    #     -o StrictHostKeyChecking=accept-new
    #     -o ProxyCommand="ssh -o StrictHostKeyChecking=accept-new -W %h:%p ubuntu@{{ lookup('env', 'HOST2_IP') }}"
  children:
    kube_control_plane:
      hosts:
        node1: {}
        # node2: {}
    kube_node:
      hosts:
        node1: {}
        # node2: {}
    etcd:
      hosts:
        node1: {}
    k8s_cluster:
      children:
        kube_control_plane: {}
        kube_node: {}
