vm_cpus: 1
vm_memory_mb: 2048
vm_name: k8s-node
vm_ip: 192.168.122.10
vm_gateway: 192.168.122.1
vm_image_src: "{{ playbook_dir }}/../packer/output-k8s-node/k8s-node.qcow2"
vm_image_dest: /var/lib/libvirt/images/k8s-node.qcow2
ssh_public_key_file: ~/.ssh/id_rsa.pub
